// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eadmvidnurfhylvoswkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhZG12aWRudXJmaHlsdm9zd2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzMwNjQsImV4cCI6MjA2OTc0OTA2NH0.o8blJEhs64vLi3Q3bfpX1A9HohaIUEhl-G9kBcACCEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});